# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build with Bun

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "export PATH=$HOME/.bun/bin:$PATH" >> $GITHUB_PATH

    - name: Verify Bun installation
      run: ~/.bun/bin/bun --version

    - name: Install dependencies
      run: ~/.bun/bin/bun install

    - name: Build project
      run: ~/.bun/bin/bun build src/main.js --outdir=dist

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: Natsuka
        path: dist/
      
